# This script is used by the Travis-CI (continuous integration) testing
# framework to run SimulationCrafts tests with every GitHub push or pull-request.
language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  # Each line is a separate build in the build matrix. A build in the build
  # matrix is defined by the environment variables defined on the line, which
  # should be space-delimited. For example,
  # - ABC=ON DEF=OFF GHI=ON
  
# matrix:
#   exclude:
#     - os: osx
#       compiler: gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:duggan/bats -y; fi
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq bats; fi

install:
  - cd engine
  - make -j8
  - cd ..

script:
  ## Test SimulationCraft.
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then cd tests; fi
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then ./run.sh enemies.bats; fi
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then ./run.sh classes.bats; fi

  ## Make sure we can install with no issues.
  ## - sudo make -j8 install
