# This script is used by the Travis-CI (continuous integration) testing
# framework to run SimulationCrafts tests with every GitHub push or pull-request.
language: cpp

branches:
  only:
    - legion-dev
    
# Enable Trusty (Ubuntu 14.04 LTS) Beta
sudo: required
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

#env:
  # Each line is a separate build in the build matrix. A build in the build
  # matrix is defined by the environment variables defined on the line, which
  # should be space-delimited. For example,
  # - ABC=ON DEF=OFF GHI=ON
  
matrix:
 exclude:
   - os: osx
     compiler: gcc
   - os: linux
     compiler: clang

before_install:
  # Install bats
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:duggan/bats -y && sudo apt-get update -qq && sudo apt-get install -qq bats; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install bats coreutils; fi

  # Install valgrind on Linux
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq valgrind; fi

notifications:
  irc:
    channels:
      - "irc.gamers-irc.org#simulationcraft"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
    on_success: never # default: always

install:
  # Build SimulationCraft
  - make DEBUG=1 -C engine -j 2

script:
  # Valgrind a raid profile with Linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then valgrind --tool=memcheck --show-reachable=yes --leak-check=summary ./engine/simc Raid_T18H.simc iterations=5 threads=1 output=/dev/null; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then valgrind --tool=memcheck --show-reachable=yes --leak-check=summary ./engine/simc Raid_T18H.simc iterations=5 threads=1 fight_style=HelterSkelter output=/dev/null; fi

  # Test SimulationCraft.
  - cd tests
  - ./run.sh enemies.bats
  - ./run.sh classes.bats
